Name:           ros-hydro-pr2-arm-kinematics
Version:        1.0.2
Release:        0%{?dist}
Summary:        ROS pr2_arm_kinematics package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_arm_kinematics
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-angles
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-kdl-parser
Requires:       ros-hydro-moveit-core
Requires:       ros-hydro-moveit-msgs
Requires:       ros-hydro-pluginlib
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-tf-conversions
Requires:       ros-hydro-urdf
BuildRequires:  ros-hydro-angles
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-kdl-parser
BuildRequires:  ros-hydro-moveit-core
BuildRequires:  ros-hydro-moveit-msgs
BuildRequires:  ros-hydro-pluginlib
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-tf-conversions
BuildRequires:  ros-hydro-urdf

%description
This package provides a kinematics implementation for the PR2 robot. It can be
used to compute forward and inverse kinematics.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Sun Sep 07 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.2-0
- Autogenerated by Bloom

