Name:           ros-jade-pr2-arm-kinematics
Version:        1.0.8
Release:        0%{?dist}
Summary:        ROS pr2_arm_kinematics package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_arm_kinematics
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-angles
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-kdl-parser
Requires:       ros-jade-moveit-core
Requires:       ros-jade-moveit-msgs
Requires:       ros-jade-pluginlib
Requires:       ros-jade-roscpp
Requires:       ros-jade-tf-conversions
Requires:       ros-jade-urdf
BuildRequires:  ros-jade-angles
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cmake-modules
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-kdl-parser
BuildRequires:  ros-jade-moveit-core
BuildRequires:  ros-jade-moveit-msgs
BuildRequires:  ros-jade-pluginlib
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-tf-conversions
BuildRequires:  ros-jade-urdf

%description
This package provides a kinematics implementation for the PR2 robot. It can be
used to compute forward and inverse kinematics.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Mon Aug 08 2016 Devon Ash <dash@clearpathrobotics.com> - 1.0.8-0
- Autogenerated by Bloom

